### ISSUE TITLE
LDAP Group synchronisation

### ISSUE THREAD

**Issue by ClundXIII** [mumble-voip/mumble-scripts#24]
Hi,

do you think it is possible to synchronize groups? In case of my setup I would like to have all groups that I created in mumble manually to be added or removed upon login. With the cn of the group being the groupname in mumble.

I have never done anything with mumble / ice, but I have used python quite a bit. If you give me a short snippet of how to add / remove groups I'll implement it myself and send a PR.

**Comment by Kissaki** [comment]
Technically possible? Yes.

I also don’t have anything against it conceptually. It could definitely be useful.

Maybe a configurable group prefix would be helpful in keeping the groups identifyable within Mumble ACL configuration if the administrator intends to mix LDAP groups and Mumble groups.

Personally I do not have anything set up where I could test it though.

**Comment by binooetomo** [comment]
I'm quite sure that you want the same goal that I want.
Just ... since I don't know LDAP, I want build my system based on Django.

My Approach will :
1. Use PreExec of systemd to clear all murmur db, keep the db vanilla state and
2. Whenever Authenticator receive auth request, forward it to backend
3. If backend found him/her is legal, it'l directly query to murmur if channel, group etc is available in murmur. If not, create. send response to authentocator

4. authenticator send auth respond to murmur.

In my case, backend is Django. I'm trying adopting Mumble-Django.

Things that I can not solve is :
1. How to make murmur to always REJECT user (not SuperUser) whenever there is no Authenticator connected.

2. From most of authenticator examples, looks like it detect whenever a Virtual server(s) is booted and will connect to it. But How authenticator deside which user is coming from which Virtual Server?

**Comment by ClundXIII** [comment]
@binooetomo 
can you contact me via email: simon@clundxiii.com

I would like to discuss the implementation quickly via some kind of voicechat (preferably mumble). To avoid a very lengthy thread about that.

**Comment by RenWal** [comment]
If this is still relevant, you could try PR #28, which we use on our local sever to synchronize groups

**Comment by ClundXIII** [comment]
We dropped mumble in favour of web-based audio and videochats

The PR would not work for us since we use groupOfUniqueNames. However, porting this to us would be trivial. Thank you anyway!
